eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/

spring:
  sql:
    init:
      mode: never
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/raimysqldb
    username: root
    password: 84ankit84
microservice:
  payment-service:
    endpoints:
      fetchPaymentById:
        uri:http://PAYMENT-SERVICE/payments/
  user-service:
    endpoints:
      fetchUserById:
        uri:http://USER-SERVICE/userservice/
test:
  input: 1
